language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "10"
deploy:
  provider: pages
  # Note: change "docs" to the directory where your gatsby-site lives, if necessary
  script:
    - npm install
    - gh-pages -d public -r https://$GITHUB_TOKEN@github.com/ayan-b/blog.git
  skip_cleanup: true
  on:
    branch: master
